"""update table name

Revision ID: 4cf53386cc75
Revises: 630d6ca4fc52
Create Date: 2022-03-14 00:07:40.213349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cf53386cc75'
down_revision = '630d6ca4fc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_post', sa.String(length=140), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Blogs_timestamp'), 'Blogs', ['timestamp'], unique=False)
    op.drop_index('ix_blog_timestamp', table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blog_post', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='blog_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_pkey')
    )
    op.create_index('ix_blog_timestamp', 'blog', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_Blogs_timestamp'), table_name='Blogs')
    op.drop_table('Blogs')
    # ### end Alembic commands ###
