"""empty message

Revision ID: cf47a2cad78f
Revises: 2522194fe5e0
Create Date: 2022-03-16 00:31:10.415108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf47a2cad78f'
down_revision = '2522194fe5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_admin_id_fkey', 'blog', type_='foreignkey')
    op.drop_column('blog', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('blog_admin_id_fkey', 'blog', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###
